### ISSUE TITLE
Шопотом

### ISSUE THREAD

**Issue by Sergei1filat** [RHVoice/Russian#1]
Привет

**Comment by Sergei1filat** [comment]
Привет

**Comment by zstanecic** [comment]
Добрый день!
Поскольку проблема не была правильно сформулирована, и не относится никак к поддержке русского языка, а скорее какого-то неопределенного голоса, закрываю тикет. 
Прошу уточнить пробему и повторно открыть тикет в нужном месте. 
Желаю Хороший остаток дня,
Звонимир Станечич
